pkgload::load_all(".")
usethis::use_package("shiny")
usethis::use_package("pkgload")
usethis::use_package("shinythemes")
usethis::use_package("epiparameter")
usethis::use_package("htmltools")
epiparameterDashboard()
